"""Agent status configuration — spinner frames and working phrases."""

SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]

WORKING_PHRASES = [
    "Mining diamonds...",
    "Untangling spaghetti...",
    "Consulting the AI gods...",
    "Summoning the neurons...",
    "Teaching pixels to think...",
    "Shuffling some electrons...",
    "Asking the rubber duck...",
    "Negotiating with the compiler...",
    "Counting imaginary bytes...",
    "Polishing the neural network...",
    "Herding tokens...",
    "Chasing a runaway semicolon...",
    "Feeding the AI hamster...",
    "Searching the void...",
    "Connecting the brain cells...",
    "Convincing the code to work...",
    "Sacrificing a few electrons...",
    "Brewing some algorithms...",
    "Waking up the neurons...",
    "Untangling the code noodles...",
    "Compressing the chaos...",
    "Fighting the bugs...",
    "Negotiating with reality...",
    "Loading suspicious amounts of intelligence...",
    "Summoning forbidden knowledge...",
    "Looking under the digital couch...",
    "Asking the silicon oracle...",
    "Turning coffee into code...",
    "Aligning the semicolons...",
    "Hunting for missing brackets...",
    "Performing computational wizardry...",
    "Recalculating everything...",
    "Making the electrons behave...",
    "Inspecting the matrix...",
    "Searching for the last bug...",
    "Convincing the CPU this was intentional...",
    "Counting tokens...",
    "Rearranging the digital furniture...",
    "Doing suspiciously intelligent things...",
    "Thinking at approximately light speed...",
    "Making questionable architectural decisions...",
    "Turning chaos into code...",
    "Negotiating with the garbage collector...",
    "Bribing the compiler...",
    "Looking for the good timeline...",
    "Consulting ancient documentation...",
    "Searching Stack Overflow spiritually...",
    "Asking nicely for the code to work...",
    "Removing the invisible bug...",
    "Deploying brain.exe...",
    "Initializing questionable genius...",
    "Generating excessive amounts of computation...",
    "Checking if it works on my machine...",
    "Summoning more RAM...",
    "Digging through the codebase...",
    "Following the suspicious function...",
    "Hunting down that one weird edge case...",
    "Making the terminal nervous...",
    "Calculating absolutely everything...",
    "Teaching the code some manners...",
    "Turning thoughts into tokens...",
]
